### ISSUE TITLE
error cdn-minio | Fatal glibc error: CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by yagi339** [mstgnz/go-minio-cdn#6]
<img width="912" alt="Screenshot 2024-09-16 at 17 00 28" src="https://github.com/user-attachments/assets/36a9f12e-5ff6-467e-a80b-08eba0adc7ad">
I just build again today but it come with this error please advisor
<img width="912" alt="Screenshot 2024-09-16 at 17 00 28" src="https://github.com/user-attachments/assets/ee154f62-920f-41b6-a3eb-f3ecbb795a93">

**Comment by mstgnz** [comment]
`direver: none` prevents the container from logging, the reason we use this is that the cdn application is subjected to constant file imports, so the log files are bloated. deactivating the logs eliminates this problem.

On both Mac Os and Linux (ubuntu) this project works flawlessly. In fact, this application is used by a very comprehensive insurance and automotive company.

If your operating system generates errors for this application, you can comment out the 
```go
logging
    driver: none
```
lines in the docker-compose.yml file and then run `docker-compose up -d`
